HomePage-Label:
  style: 'color: darkblue;font-size: 16px;qproperty-alignment:AlignCenter;; font-weight
    : 900;border-radius: 5px;border: 2px solid black;background-color : tan;'
Lang: ch
Main:
  sizes:
  - 1200
  - 800
QGroupBox:
  max-height: 350
  style: 'QGroupBox::title { subcontrol-origin: margin; subcontrol-position: top center;
    padding: 0 3px; qproperty-titleAlign: center;}'
QSplitter:
  sizes:
  - 100
  - 1000
Theme:
  name: light_purple_500.xml
Title:
  style: 'qproperty-alignment: AlignHCenter; font-size : 16px;'
